Fix arg parsing

diff --git a/xdeb b/xdeb
--- a/xdeb
+++ b/xdeb
@@ -65,7 +65,7 @@ genrdeps() {
 		objdump -p "${f}" | grep NEEDED | awk '{print $2}'
 	done | sort -u | while read -r lib; do
 		# Ignore libraries provided by current package
-		[ ! -z "$(find "${XDEB_DESTDIR}" -name "${lib}")" ] && continue
+		[ -n "$(find "${XDEB_DESTDIR}" -name "${lib}")" ] && continue
 
 		_lib=$(echo "${lib}" | sed -E 's|\+|\\+|g')
 		rdep="$(grep -E -m1 "^${_lib}[[:blank:]]+.*$" "${XDEB_SHLIBS}" | cut -d ' ' -f2)"
@@ -99,15 +99,15 @@ usage: xdeb [-S] [-d] [-Sd] [--deps] ... FILE
   -e                       # Remove empty directories
   -m                       # Add the -32bit suffix
   -i                       # Ignore file conflicts
-  --deps                   # Add manual dependencies
-  --arch                   # Add an arch for the package to run on
-  --revision               # Set package revision. Alternative to -R, to not remove the repodata
+  --deps=                  # Add manual dependencies
+  --arch=                  # Add an arch for the package to run on
+  --revision= | --rev=     # Set package revision. Alternative to -R, to not remove the repodata
   --help | -h              # Show this page
 
 example:
   xdeb -Cq                 # Remove all files and quit
   xdeb -Sd FILE            # Sync depdendency list and create package
-  xdeb --deps 'ar>0' FILE  # Add ar as a manual dependency and create package
+  xdeb --deps='ar>0' FILE  # Add ar as a manual dependency and create package
 EOF
 }
 
@@ -124,10 +124,15 @@ mkdir -p "${XDEB_PKGROOT}"
 
 while [ "${#}" != "0" ]; do
 	case "${1}" in
-		--deps) shift; XDEB_DEPENDENCIES="${1}"; continue;;
-		--arch) shift; archs="${1}"; continue;;
-		--revision) shift; revision="${1}"; continue;;
+		--deps|--arch|--revision)
+			log_failure "${1} invalid. Use ${1}=... instead"; exit 1; continue;;
+
+		--deps=*) XDEB_DEPENDENCIES="${XDEB_DEPENDENCIES}${1#*=} "; shift; continue;;
+		--arch=*) archs="${1#*=}"; shift; continue;;
+		--revision=*|--rev=*) revision="${1#*=}"; shift; continue;;
+
 		--help) usage; exit 0;;
+		--*) log_failure "invalid option '${1}'"; usage; exit 1;;
 		-*);;
 		# Posix getopt stops after first non-option
 		*) [ "${#}" = 1 ] && XDEB_BASEPKG="${1}"; break;;
@@ -176,7 +181,7 @@ done
 
 [ "${XDEB_OPT_EXTRACT}" = true ] && {
 	# Does the filename end with .deb? Is the file readable?
-	echo "${XDEB_BASEPKG}" | grep -q "\.deb$" || [ -r "${XDEB_BASEPKG}" ] || {
+	echo "${XDEB_BASEPKG}" | grep -q "\.deb$" && [ -r "${XDEB_BASEPKG}" ] || {
 		log_critical "Last argument has to point to an existing deb package"
 		exit 1
 	}
@@ -220,10 +225,15 @@ esac
 
 [ "${XDEB_OPT_DEPS}" = true ] && {
 	XDEB_DEPENDENCIES="${XDEB_DEPENDENCIES} $(genrdeps)"
+}
+
+# Remove trailing space
+XDEB_DEPENDENCIES="${XDEB_DEPENDENCIES%* }"
+[ -n "${XDEB_DEPENDENCIES}" ] && {
 	log_success "Resolved dependencies (${XDEB_DEPENDENCIES})"
 }
 
-{ [ "${XDEB_OPT_CLEAN_DIR}" = true ] || [ "${XDEB_OPT_WARN_CONFLICT}" = true ]; } && {
+[ "${XDEB_OPT_CLEAN_DIR}" != true ] && [ "${XDEB_OPT_WARN_CONFLICT}" != true ] || {
 	find "${XDEB_DESTDIR}" | {
 		while read -r f; do
 			# Remove empty directories
